# Generated by Django 5.0.1 on 2024-07-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_group',
            field=models.CharField(choices=[('LVI', 'LVI'), ('UVI', 'UVI')], max_length=200, null=True),
        ),
    ]
