# Generated by Django 5.0.1 on 2024-07-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_booking_student_booking_subject_booking_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveningdate',
            name='timeslots',
            field=models.ManyToManyField(to='main.timeslot'),
        ),
        migrations.AddField(
            model_name='student',
            name='subjects',
            field=models.ManyToManyField(to='main.subject'),
        ),
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(to='main.teacher'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='subjects',
            field=models.ManyToManyField(to='main.subject'),
        ),
    ]
