# Generated by Django 5.0.1 on 2024-07-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_eveningdate_timeslots_student_subjects_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveningdate',
            name='timeslots',
            field=models.ManyToManyField(null=True, to='main.timeslot'),
        ),
    ]
