# Generated by Django 5.0.1 on 2024-07-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_eveningdate_timeslots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eveningdate',
            name='timeslots',
            field=models.ManyToManyField(to='main.timeslot'),
        ),
    ]
