# Generated by Django 5.0.1 on 2024-07-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_eveningdate_timeslots'),
    ]

    operations = [
        migrations.AddField(
            model_name='eveningdate',
            name='year_group',
            field=models.CharField(choices=[('LVI', 'LVI'), ('UVI', 'UVI')], max_length=200, null=True),
        ),
    ]
