# Generated by Django 5.0.1 on 2024-07-23 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_eveningdate_year_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.eveningdate'),
        ),
    ]
