# Generated by Django 5.0.1 on 2024-08-02 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_booking_date_alter_booking_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.building'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.room'),
        ),
    ]
