# Generated by Django 5.0.1 on 2024-08-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_teacher_building_alter_teacher_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='subject',
        ),
    ]
