# Generated by Django 5.0.1 on 2024-08-20 14:02

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Booking = apps.get_model("main", "Booking")
    for row in Booking.objects.all():
        row.booking_id = uuid.uuid4()
        row.save(update_fields=["booking_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_booking_booking_id'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
